# Generated by Django 6.0.3 on 2026-05-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecategory_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True, verbose_name='ID Thinkific')),
                ('course_name_cache', models.CharField(blank=True, max_length=255, verbose_name='Nom du cours')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible sur le site')),
            ],
            options={
                'verbose_name': 'Visibilité de cours',
                'verbose_name_plural': 'Visibilité des cours',
                'ordering': ['course_name_cache'],
            },
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='color',
            field=models.CharField(blank=True, default='#6366F1', help_text="Couleur hex, ex: #6366F1 — utilisee si aucune image n'est definie", max_length=20, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.CharField(blank=True, help_text="Affichee sous le nom sur la page d'accueil", max_length=200, verbose_name='Description courte'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(blank=True, help_text="Image d'en-tete de la carte (recommande : 400x220 px)", upload_to='categories/', verbose_name='Image'),
        ),
    ]
