# Generated by Django 6.0.3 on 2026-05-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_coursevisibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleCategoryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_id', models.IntegerField(verbose_name='ID bundle Thinkific')),
                ('bundle_name_cache', models.CharField(blank=True, max_length=255, verbose_name='Nom (cache)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_memberships', to='courses.coursecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Bundle de la catégorie',
                'verbose_name_plural': 'Bundles de la catégorie',
                'unique_together': {('category', 'bundle_id')},
            },
        ),
    ]
