# Generated by Django 6.0.3 on 2026-05-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_bundle_category_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Optionnel — fond de la carte (recommandé : 800×400 px)', null=True, upload_to='course_groups/', verbose_name='Image')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Groupe de cours',
                'verbose_name_plural': 'Groupes de cours',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(verbose_name='ID cours Thinkific')),
                ('course_name_cache', models.CharField(blank=True, max_length=255, verbose_name='Nom (cache)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='courses.coursegroup', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Cours du groupe',
                'verbose_name_plural': 'Cours du groupe',
                'unique_together': {('group', 'course_id')},
            },
        ),
    ]
