# Generated by Django 6.0.3 on 2026-05-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Catégorie à laquelle appartient ce groupe — filtre automatique sur la page cours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_groups', to='courses.coursecategory', verbose_name='Catégorie parente'),
        ),
    ]
