"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.utils.translation import gettext_lazy as _

from django.conf.locale import LANG_INFO

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# env = environ.Env(
#     # set casting, default value
#     PRODUCTION=(bool, False)
# )
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

PRODUCTION = os.environ.get("PRODUCTION", "False").lower() in ("true", "1", "yes")

if PRODUCTION:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Railway termine SSL au niveau du load balancer — pas de redirect Django
    SECURE_SSL_REDIRECT = False

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY","dev")

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Railway injecte RAILWAY_PUBLIC_DOMAIN (ex: koulakay-production.up.railway.app)
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
if _railway_domain:
    ALLOWED_HOSTS.append(_railway_domain)

# Nécessaire pour que le healthcheck GET /health/ ne soit pas bloqué par Django.
# Railway envoie les requêtes healthcheck depuis healthcheck.railway.app.
ALLOWED_HOSTS += ['0.0.0.0', 'healthcheck.railway.app']

# Domaines supplémentaires définis manuellement (séparés par virgule dans l'env)
_extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(',') if h.strip()]

CORS_ALLOW_ALL_ORIGINS = not PRODUCTION
if PRODUCTION:
    CORS_ALLOWED_ORIGINS = [f'https://{_railway_domain}'] if _railway_domain else []
    _extra_cors = os.environ.get('CORS_ALLOWED_ORIGINS', '')
    if _extra_cors:
        CORS_ALLOWED_ORIGINS += [o.strip() for o in _extra_cors.split(',') if o.strip()]

CSRF_TRUSTED_ORIGINS = ['http://localhost', 'http://127.0.0.1']
if _railway_domain:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_domain}')
_extra_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if _extra_origins:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra_origins.split(',') if o.strip()]

# if DEBUG == False:
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#     SESSION_COOKIE_DOMAIN = ".devfundme"
#     SECURE_SSL_REDIRECT = True
#     SESSION_COOKIE_SECURE = True
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'django_admin_generator',
    #'django_browser_reload',
    'crispy_forms',
    'crispy_bootstrap4',
    'accounts',
    #'payment',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'import_export',
    'pages',
    'courses',
    'payment',
    "anymail",

    # Optional -- requires install using `django-allauth[socialaccount]`.
    # 'allauth.socialaccount',
    # ... include the providers you want to enable:
    # 'allauth.socialaccount.providers.agave',
    # 'allauth.socialaccount.providers.amazon',
    # 'allauth.socialaccount.providers.amazon_cognito',
    # 'allauth.socialaccount.providers.angellist',
    # 'allauth.socialaccount.providers.apple',
    # 'allauth.socialaccount.providers.asana',
    # 'allauth.socialaccount.providers.auth0',
    # 'allauth.socialaccount.providers.authentiq',
    # 'allauth.socialaccount.providers.baidu',
    # 'allauth.socialaccount.providers.basecamp',
    # 'allauth.socialaccount.providers.battlenet',
    # 'allauth.socialaccount.providers.bitbucket_oauth2',
    # 'allauth.socialaccount.providers.bitly',
    # 'allauth.socialaccount.providers.box',
    # 'allauth.socialaccount.providers.cilogon',
    # 'allauth.socialaccount.providers.clever',
    # 'allauth.socialaccount.providers.coinbase',
    # 'allauth.socialaccount.providers.dataporten',
    # 'allauth.socialaccount.providers.daum',
    # 'allauth.socialaccount.providers.digitalocean',
    # 'allauth.socialaccount.providers.dingtalk',
    # 'allauth.socialaccount.providers.discord',
    # 'allauth.socialaccount.providers.disqus',
    # 'allauth.socialaccount.providers.douban',
    # 'allauth.socialaccount.providers.doximity',
    # 'allauth.socialaccount.providers.draugiem',
    # 'allauth.socialaccount.providers.drip',
    # 'allauth.socialaccount.providers.dropbox',
    # 'allauth.socialaccount.providers.dwolla',
    # 'allauth.socialaccount.providers.edmodo',
    # 'allauth.socialaccount.providers.edx',
    # 'allauth.socialaccount.providers.eventbrite',
    # 'allauth.socialaccount.providers.eveonline',
    # 'allauth.socialaccount.providers.evernote',
    # 'allauth.socialaccount.providers.exist',
    # 'allauth.socialaccount.providers.facebook',
    # 'allauth.socialaccount.providers.feedly',
    # 'allauth.socialaccount.providers.figma',
    # 'allauth.socialaccount.providers.fivehundredpx',
    # 'allauth.socialaccount.providers.flickr',
    # 'allauth.socialaccount.providers.foursquare',
    # 'allauth.socialaccount.providers.frontier',
    # 'allauth.socialaccount.providers.fxa',
    # 'allauth.socialaccount.providers.gitea',
    # 'allauth.socialaccount.providers.github',
    # 'allauth.socialaccount.providers.gitlab',
    # 'allauth.socialaccount.providers.globus',
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.gumroad',
    # 'allauth.socialaccount.providers.hubic',
    # 'allauth.socialaccount.providers.instagram',
    # 'allauth.socialaccount.providers.jupyterhub',
    # 'allauth.socialaccount.providers.kakao',
    # 'allauth.socialaccount.providers.lemonldap',
    # "allauth.socialaccount.providers.lichess",
    # 'allauth.socialaccount.providers.line',
    # 'allauth.socialaccount.providers.linkedin',
    # 'allauth.socialaccount.providers.linkedin_oauth2',
    # 'allauth.socialaccount.providers.mailchimp',
    # 'allauth.socialaccount.providers.mailru',
    # 'allauth.socialaccount.providers.mediawiki',
    # 'allauth.socialaccount.providers.meetup',
    # 'allauth.socialaccount.providers.miro',
    # 'allauth.socialaccount.providers.microsoft',
    # 'allauth.socialaccount.providers.naver',
    # 'allauth.socialaccount.providers.nextcloud',
    # 'allauth.socialaccount.providers.notion',
    # 'allauth.socialaccount.providers.odnoklassniki',
    # 'allauth.socialaccount.providers.openid',
    # 'allauth.socialaccount.providers.openid_connect',
    # 'allauth.socialaccount.providers.openstreetmap',
    # 'allauth.socialaccount.providers.orcid',
    # 'allauth.socialaccount.providers.patreon',
    # 'allauth.socialaccount.providers.paypal',
    # 'allauth.socialaccount.providers.persona',
    # 'allauth.socialaccount.providers.pinterest',
    # 'allauth.socialaccount.providers.pocket',
    # "allauth.socialaccount.providers.questrade",
    # 'allauth.socialaccount.providers.quickbooks',
    # 'allauth.socialaccount.providers.reddit',
    # 'allauth.socialaccount.providers.robinhood',
    # 'allauth.socialaccount.providers.salesforce',
    # 'allauth.socialaccount.providers.sharefile',
    # 'allauth.socialaccount.providers.shopify',
    # 'allauth.socialaccount.providers.slack',
    # 'allauth.socialaccount.providers.snapchat',
    # 'allauth.socialaccount.providers.soundcloud',
    # 'allauth.socialaccount.providers.spotify',
    # 'allauth.socialaccount.providers.stackexchange',
    # 'allauth.socialaccount.providers.steam',
    # 'allauth.socialaccount.providers.stocktwits',
    # 'allauth.socialaccount.providers.strava',
    # 'allauth.socialaccount.providers.stripe',
    # 'allauth.socialaccount.providers.telegram',
    # 'allauth.socialaccount.providers.trainingpeaks',
    # 'allauth.socialaccount.providers.trello',
    # 'allauth.socialaccount.providers.tumblr',
    # 'allauth.socialaccount.providers.twentythreeandme',
    # 'allauth.socialaccount.providers.twitch',
    # 'allauth.socialaccount.providers.twitter',
    # 'allauth.socialaccount.providers.twitter_oauth2',
    # 'allauth.socialaccount.providers.untappd',
    # 'allauth.socialaccount.providers.vimeo',
    # 'allauth.socialaccount.providers.vimeo_oauth2',
    # 'allauth.socialaccount.providers.vk',
    # 'allauth.socialaccount.providers.wahoo',
    # 'allauth.socialaccount.providers.weibo',
    # 'allauth.socialaccount.providers.weixin',
    # 'allauth.socialaccount.providers.windowslive',
    # 'allauth.socialaccount.providers.xing',
    # 'allauth.socialaccount.providers.yahoo',
    # 'allauth.socialaccount.providers.yandex',
    # 'allauth.socialaccount.providers.ynab',
    # 'allauth.socialaccount.providers.zoho',
    # 'allauth.socialaccount.providers.zoom',
    # 'allauth.socialaccount.providers.okta',
    # 'allauth.socialaccount.providers.feishu',
    # "allauth.socialaccount.providers.atlassian",
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # sert les fichiers statiques sans Nginx
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django_browser_reload.middleware.BrowserReloadMiddleware',

    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.locale.LocaleMiddleware',

#     # "corsheaders.middleware.CorsMiddleware",
#     # "django.middleware.common.CommonMiddleware",

#     # # 'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#      'django.contrib.auth.middleware.AuthenticationMiddleware',
#      'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 15,

#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.BasicAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.TokenAuthentication',
#     ],

#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAdminUser',
#     ],

#     'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema' 
# }

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # ` media`
                'django.template.context_processors.media',
                'pages.context_processors.site_config',
                
                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


_database_url = os.environ.get('DATABASE_URL', '')
if _database_url:
    # Railway (et tout hébergeur 12-factor) fournit DATABASE_URL automatiquement
    DATABASES = {
        'default': dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            ssl_require=PRODUCTION,
        )
    }
else:
    # Développement local → SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]
# EMAIL_BACKEND défini plus bas via anymail (ne pas redéfinir ici)

SOCIALACCOUNT_QUERY_EMAIL = True

ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Nouvelle syntaxe allauth >= 65.x
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['first_name*', 'last_name*', 'email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION=True

AUTH_USER_MODEL = 'accounts.User'

ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_FORMS = {
    'add_email': 'allauth.account.forms.AddEmailForm',
    'change_password': 'allauth.account.forms.ChangePasswordForm',
    'disconnect': 'allauth.socialaccount.forms.DisconnectForm',
    'login': 'allauth.account.forms.LoginForm',
    'reset_password': 'allauth.account.forms.ResetPasswordForm',
    'reset_password_from_key': 'allauth.account.forms.ResetPasswordKeyForm',
    'set_password': 'allauth.account.forms.SetPasswordForm',
    'signup': 'accounts.forms.CustomSignupForm',
    'user_token': 'allauth.account.forms.UserTokenForm',
}


ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret':    os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key':       '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

LOGIN_REDIRECT_URL = "/"           # fallback si pas de ?next=
LOGIN_URL = '/accounts/login/'
# Allauth respecte automatiquement ?next= pour login et signup
# ACCOUNT_SIGNUP_REDIRECT_URL non défini → utilise LOGIN_REDIRECT_URL comme fallback
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANG_INFO.update({
    'ht': {
        'bidi': False,  # Indique que la langue se lit de gauche à droite
        'code': 'ht',
        'name': 'Haitian Creole',
        'name_local': 'Kreyòl Ayisyen',
    }
})

# Specify the list of languages you want to support
LANGUAGES = [
    ('en', _('English')),
    ('fr', _('Français')),
    ('es', _('Español')),
    ('ht', _('Kreyòl Ayisyen')),
    # Add more languages as needed
]

LANGUAGE_CODE = 'fr'

MODELTRANSLATION_DEFAULT_LANGUAGE = 'fr'
MODELTRANSLATION_LANGUAGES = ('fr', 'en', 'es', 'ht')

USE_I18N = True

USE_L10N = True

# Specify the directory where your translation files will be stored
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

TIME_ZONE = 'UTC'

USE_TZ = True

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"

CRISPY_TEMPLATE_PACK = "bootstrap4"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if DEBUG:
    # En développement : storage standard (pas besoin de collectstatic)
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # En production : whitenoise compresse et hache les fichiers
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

STATICFILES_DIRS = [
    BASE_DIR / "config" / "static",
]

ADMIN_USER=os.getenv("ADMIN_USER","admin@koulakay.ht")
ADMIN_PASSWORD=os.getenv("ADMIN_PASSWORD","admin12345")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SITE_ID = 1


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PHONENUMBER_DEFAULT_FORMAT = "INTERNATIONAL"

THINKIFIC = {
    'AUTH_TOKEN': os.getenv('THINKIFIC_SECRET_KEY', ''),
    'SITE_ID': os.getenv('SITE_ID', 'koulakay'),
    'SECRET_KEY': os.getenv('THINKIFIC_WEBHOOK_SECRET', ''),
    # SSO Signing Secret (API Access Token → SSO Signing Secret)
    # Différent de AUTH_TOKEN — utilisé pour signer les JWT SSO
    'SSO_SECRET': os.getenv('THINKIFIC_SSO_SECRET', os.getenv('THINKIFIC_WEBHOOK_SECRET', '')),
}

PLOPPLOP = {
    'CLIENT_ID': os.getenv('PLOPPLOP_CLIENT_ID', ''),
    'BASE_URL': 'https://plopplop.solutionip.app',
    'RETURN_URL': os.getenv('PLOPPLOP_RETURN_URL', 'https://koulakay.ht/payment/retour/'),
}

STRIPE = {
    'PUBLIC_KEY': os.getenv('STRIPE_PUBLIC_KEY', ''),
    'SECRET_KEY': os.getenv('STRIPE_SECRET_KEY', ''),
    'WEBHOOK_SECRET': os.getenv('STRIPE_WEBHOOK_SECRET', ''),
}

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'KouLakay <noreply@koulakay.ht>')
SERVER_EMAIL       = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@koulakay.ht')

# Email via Resend (anymail) — fallback console en dev si pas de clé
_resend_key = os.getenv('RESEND_API_KEY', '')

if _resend_key:
    EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
    ANYMAIL = {
        "RESEND_API_KEY": _resend_key,
    }
else:
    # Pas de clé Resend → affiche les emails dans la console (dev)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

if DEBUG:
    INSTALLED_APPS += ['django_browser_reload']
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']

# ─────────────────────────────────────────────
# JAZZMIN — Admin KouLakay
# ─────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # Titre affiché dans la barre du navigateur
    "site_title": "KouLakay Admin",
    "site_header": "KouLakay",
    "site_brand": "KouLakay",

    # Logo (chemin relatif à STATIC_URL)
    "site_logo": "logo/koulakay.png",
    "login_logo": "logo/koulakay.png",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "logo/koulaka.png",

    # Texte de bienvenue sur la page de login
    "welcome_sign": "Administration KouLakay",

    # Copyright
    "copyright": "KouLakay — Plateforme éducative haïtienne",

    # Recherche globale dans les modèles
    "search_model": ["accounts.User", "courses.Enrollment", "payment.Transaction"],

    # Champ utilisateur dans la navbar
    "user_avatar": None,

    # ── Topbar ──
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Voir le site", "url": "/fr/", "new_window": True},
        {"name": "Utilisateurs", "url": "admin:accounts_customuser_changelist", "permissions": ["accounts.view_customuser"]},
    ],

    # ── Sidebar ──
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Icônes par app/modèle (Material Design Icons via FontAwesome)
    "icons": {
        "auth":                          "fas fa-users-cog",
        "auth.user":                     "fas fa-user",
        "auth.Group":                    "fas fa-users",
        "accounts.User":           "fas fa-user-graduate",
        "courses.Enrollment":            "fas fa-graduation-cap",
        "payment.Transaction":           "fas fa-money-bill-wave",
        "payment.Payment":               "fas fa-credit-card",
        "pages.SiteConfig":              "fas fa-cog",
        "allauth.account.EmailAddress":  "fas fa-envelope",
        "sites.Site":                    "fas fa-globe",
        "socialaccount.SocialApp":       "fas fa-share-alt",
        "socialaccount.SocialAccount":   "fas fa-id-badge",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ── UI ──
    "related_modal_active": True,
    "custom_css": "styles/admin_koulakay.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # Ordre des apps dans la sidebar
    "order_with_respect_to": [
        "pages",
        "accounts",
        "courses",
        "payment",
        "allauth",
        "auth",
        "sites",
    ],

    # Liens rapides dans le menu latéral
    "custom_links": {
        "courses": [
            {
                "name": "Voir les cours",
                "url": "/fr/courses/courses/",
                "icon": "fas fa-book-open",
                "new_window": True,
            }
        ],
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    # Couleurs principales — palette KouLakay brun/ambre
    "brand_colour": "navbar-dark",
    "accent":       "accent-warning",

    # Navbar couleur sombre (brun foncé)
    "navbar":       "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,

    # Sidebar sombre brun (surcharge via CSS custom)
    "sidebar":             "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    # Layout — thème clair comme base (le CSS custom applique le brun par-dessus)
    "theme":    "flatly",
    "default_theme_mode": "light",

    # Boutons
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-warning",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },

    # Actions
    "actions_sticky_top": True,
}